# Generated by Django 5.2.11 on 2026-02-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='stock',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
